map_type: costmap
transform_tolerance: 0.2
obstacle_range: <number> # range in meters at which to insert obstacles - a good value might be from 2 to 3 meters
raytrace_range: <number> # range in meters at which to raytrace in order to clear cells - a good value might be 3 to 5
inflation_radius: 0.25

footprint: [[0.26, 0.18],
            [0.26, 0.014],
            [0.31, 0.014],
            [0.31, -0.014],
            [0.26, -0.014],
            [0.26, -0.18],
            [-0.27, -0.18],
            [-0.27, 0.18]]

observation_sources: base_scan

base_scan: {sensor_frame: <laser_link>, # What is the sensor's link?
            data_type: <datatype>, # try to find out the datatype
            topic: /<lasertopic>, # what is the laser topic?
            marking: <true/false>, # do you want this sensor to be allowed to mark cells within the occupancy grid? 
            clearing: <true/false>, # do you want this sensor to be allowed to clear cells within the occupancy grid? 
            }

