#Independent settings for the planner's costmap
global_costmap:
    publish_voxel_map: true
    global_frame: <frame> # the global fixed frame - either map or odom
    robot_base_frame: <baseframe> # the frame to be set up for reference of the robot - e.g. base_link or base_footprint
    update_frequency: <updatefrequency> # number in hz to update the costmap - this can have a high effect on low cpu resources - a good value might be 1 - 10 this value can be lower than the one in the local costmap
    publish_frequency: 1.0
    static_map: false
    rolling_window: true
    width: <width> # width of the costmap - the higher the more cpu load - this should be higher than the local costmap as we don't often replan
    height: <height> # height of the costmap - the higher the more cpu load - this should be higher than the local costmap as we don't often replan
    resolution: 0.05
    origin_x: 0.0
    origin_y: 0.0
