#Independent settings for the local costmap
local_costmap:
    publish_voxel_map: true
    global_frame: <frame> # the global fixed frame - either map or odom
    robot_base_frame: <baseframe> # the frame to be set up for reference of the robot - e.g. base_link or base_footprint
    update_frequency: <updatefrequency> # number in hz to update the costmap - this can have a high effect on low cpu resources - a good value might be 1 - 10
    publish_frequency: 2.0
    static_map: false
    rolling_window: true
    width: <width> # width of the costmap - the higher the more cpu load
    height: <height> # height of the costmap - the higher the more cpu load
    resolution: 0.05
    origin_x: 0.0
    origin_y: 0.0
