TebLocalPlannerROS:
   
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
# global_plan_viapoint_sep: 0.2
 allow_init_with_backwards_motion: True
 max_global_plan_lookahead_dist: 1.0
 feasibility_check_no_poses: 2
# via_points_ordered: True
 exact_arc_length: True 
 wheelbase: 0.0

 # Robot
         
 max_vel_x: 0.6
 max_vel_x_backwards: 0.6
 max_vel_y: 0.6
 max_vel_theta: 1.0
 acc_lim_x: 1.0
 acc_lim_y: 1.0
 acc_lim_theta: 1.0
 min_turning_radius: 0.0 # omni-drive robot (can turn on place!)

 footprint_model: 
   type: "line"
   line_start: [-0.19, 0.0] 
   line_end: [0.19, 0.0]

 # GoalTolerance
    
 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.1
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.25 # This value must also include our robot radius, since footprint_model is set to "point".
 include_costmap_obstacles: True
 legacy_obstacle_association: True # The current version of teb_local_planner (0.6.6) seems to sometimes rotate very slowly without legacy_obstacle_association
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.0
 weight_max_vel_x: 1
 weight_max_vel_y: 1
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_y: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1 # WE HAVE A HOLONOMIC ROBOT, JUST ADD A SMALL PENALTY
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 1
 weight_dynamic_obstacle: 1

 # Homotopy Class Planner

 enable_homotopy_class_planning: False
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: False
 
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False
